export default function Page() {
  return (
    <main className="max-w-6xl mx-auto px-6 py-12">
      <div>
        <h1 className="text-4xl font-bold tracking-tight">Disclaimer Policy</h1>
      </div>

      <div className="bg-white rounded-2xl border shadow-sm p-6 md:p-10 mt-8 space-y-8 text-gray-800">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
          <p className="leading-relaxed">This Disclaimer Policy outlines the limitations of liability and responsibility regarding your use of DataPe.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. No Professional Advice</h2>
          <p className="leading-relaxed">DataPe provides AI-powered tools to query, analyze, and visualize data. The information and outputs generated by the Platform are for informational purposes only and should not be considered as professional, legal, financial, or business advice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. Accuracy of Information</h2>
          <p className="leading-relaxed">While we strive to ensure accuracy, completeness, and reliability, DataPe makes no guarantees that the results provided by the Platform are error-free or suitable for your intended use. Users are responsible for verifying the accuracy of information before making decisions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Third-Party Integrations</h2>
          <p className="leading-relaxed">DataPe may integrate with third-party databases and services. We do not control and are not responsible for the content, reliability, or availability of such external sources.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
          <p className="leading-relaxed">DataPe shall not be held liable for any losses, damages, or consequences arising directly or indirectly from your use of the Platform, including but not limited to data inaccuracies, downtime, or third-party service interruptions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Use at Your Own Risk</h2>
          <p className="leading-relaxed">By using the Platform, you acknowledge that you do so at your own risk and agree that DataPe shall not be responsible for any damages or losses incurred.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Contact Us</h2>
          <p className="leading-relaxed">For questions about this Disclaimer Policy, please contact us at:</p>
          <ul className="space-y-1 text-gray-700 leading-relaxed">
            <li><span className="font-medium">Email:</span> support@datape.ai</li>
            <li><span className="font-medium">Phone:</span> +91 8977002747</li>
          </ul>
        </section>
      </div>
    </main>
  )
}